### PR TITLE
heka-front-chat first

### PR DESCRIPTION
**Pull request by yigit-can-ozkaya**
It is not entirely done, i will implement a direct message from user's profile page and correcting chat's ui. It is not done yet

### CODE REVIEW

**Comment by yigit-can-ozkaya** [comment]
It should be okay for now

**Comment by yigit-can-ozkaya** [comment]
@BeratDamar @umutdenizsenerr can you review it?

**Comment by BeratDamar** [comment]
I reviewed your implementation. We can send a message to another user  and other user can reply that message. However, user profile page was not implemented yet, we can not select user to send a message. For now, this is sufficient for us.

Can you improve UI of chat ?  I think that we provide better experience for users while chatting.
I will merge but as I said, it will be good if you can improve desgin of chat.

Thanks for your contribution.

**Comment by yigit-can-ozkaya** [comment]
@BeratDamar thanks for the review! Yes, the UI of the chat will be improved soon

**Pull request merged**
